# Inference config (submission)
# Usage: bash scripts/run_infer.sh configs/infer.yaml

data_root: /home/jeremiah/github/UW-Madison_GI_Tract_Image_Segmentation/inputs
weights: ./outputs/train_run/best.pt
out_csv: ./outputs/submission.csv

test_dir: null
sample_submission: /home/jeremiah/github/UW-Madison_GI_Tract_Image_Segmentation/inputs/sample_submission.csv

sw_patch_d: 96
sw_patch_h: 96
sw_patch_w: 96
sw_batch_size: 1
threshold: 0.5

num_workers: 2

debug: true
